# Generated by Django 5.0 on 2024-03-23 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordered',
            name='payment_method',
            field=models.CharField(choices=[('Cash On Delivery', 'Cash On Delivery')], default='Cash On Delivery', max_length=20),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
